okta:
  client:
    orgUrl: https://dev-490242.oktapreview.com
    token: 00yFvKNm4WoGF8SXUxAr6D20Xe5V0jE9GxQ74_pKWR
security:
    oauth2:
      client:
        access-token-uri: https://dev-490242.oktapreview.com/oauth2/default/v1/token
        user-authorization-uri: https://dev-490242.oktapreview.com/oauth2/default/v1/authorize
        client-id: {clientId}
        client-secret: {clientSecret}
      resource:
        user-info-uri: https://dev-490242.oktapreview.com/oauth2/default/v1/userinfo
spring:
  profiles:
    active: @spring.profiles.active@